/**
 * Golden Snapshot Parity Tests
 *
 * Asserts that lib/terravalue-engine.js produces output identical to the
 * committed snapshots in tests/golden-snapshots.json.
 *
 * If a test fails, EITHER:
 *   (a) The engine math regressed unintentionally — fix the engine.
 *   (b) The engine math changed intentionally — re-run
 *       `node tests/generate-snapshots.js` and commit the updated snapshot
 *       file alongside the engine change. The diff in PR review shows
 *       reviewers exactly which outputs moved and by how much.
 *
 * Run: node --test tests/golden-parity.test.js
 *      OR: npm test
 */

const { describe, it } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

// Freeze time before requiring the engine. Must match generate-snapshots.js
// exactly. Any drift between these two values means snapshot regeneration
// produces output that the test then can't match.
const FROZEN_ISO = '2026-05-20T00:00:00.000Z';
const FROZEN_NOW = new Date(FROZEN_ISO).getTime();
const RealDate = Date;
Date.now = () => FROZEN_NOW;
global.Date = new Proxy(RealDate, {
  construct(target, args) {
    if (args.length === 0) return new target(FROZEN_NOW);
    return new target(...args);
  },
});
global.Date.now = () => FROZEN_NOW;

// Match generate-snapshots.js: deterministic Math.random.
function mulberry32(seed) {
  let s = seed >>> 0;
  return function() {
    s = (s + 0x6D2B79F5) >>> 0;
    let t = s;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
let _rng = mulberry32(1);
Math.random = () => _rng();
function resetRng(seed = 1) { _rng = mulberry32(seed); }

const Lib = require('../lib/terravalue-engine');

// Snapshot file is generated by tests/generate-snapshots.js.
// If this file is missing, run the generator first.
const SNAPSHOT_PATH = path.join(__dirname, 'golden-snapshots.json');
let snapshots;
try {
  snapshots = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, 'utf-8'));
} catch (err) {
  console.error('');
  console.error('  ✗ tests/golden-snapshots.json is missing or invalid.');
  console.error('    Run: node tests/generate-snapshots.js');
  console.error('');
  throw err;
}

// ─── Fixtures (kept in sync with tests/generate-snapshots.js) ──

const PARCELS = {
  roswell:     { lotSizeSqFt: 43560, canopyPct: 35, assessedValue: 200000, state: 'GA' },
  mountVernon: { lotSizeSqFt: 21780, canopyPct: 45, assessedValue: 150000, state: 'GA' },
  northRiver:  { lotSizeSqFt: 87120, canopyPct: 20, assessedValue: 500000, state: 'GA' },
  noCanopy:    { lotSizeSqFt: 10000, canopyPct: 0,  assessedValue: 80000,  state: 'GA' },
  maxCanopy:   { lotSizeSqFt: 43560, canopyPct: 80, assessedValue: 300000, state: 'GA' },
  nonGA:       { lotSizeSqFt: 30000, canopyPct: 30, assessedValue: 400000, state: 'CA' },
};

const PROJECTIONS = [
  { currentScore: 45, projectedScore: 72, timelineYears: 30, propertyValue: 500000,  currentCanopyPct: 25, lotSizeSqFt: 15000 },
  { currentScore: 20, projectedScore: 80, timelineYears: 10, propertyValue: 300000,  currentCanopyPct: 10, lotSizeSqFt: 43560 },
  { currentScore: 70, projectedScore: 70, timelineYears: 5,  propertyValue: 750000,  currentCanopyPct: 40, lotSizeSqFt: 8000 },
  { currentScore: 90, projectedScore: 95, timelineYears: 20, propertyValue: 1000000, currentCanopyPct: 60, lotSizeSqFt: 100000 },
];

const SITE_DATA = {
  high: { canopyPct: 55, hasGreenInfrastructure: true,  biodiversityNetGainPct: 15, plantWallPct: 3,   pottedPlantPct: 2,   hasErosionPlan: true,  hasBiophiliaPlan: true  },
  low:  { canopyPct: 10, hasGreenInfrastructure: false, biodiversityNetGainPct: 3,  plantWallPct: 0,   pottedPlantPct: 0,   hasErosionPlan: false, hasBiophiliaPlan: false },
  mid:  { canopyPct: 30, hasGreenInfrastructure: true,  biodiversityNetGainPct: 8,  plantWallPct: 1,   pottedPlantPct: 0.5, hasErosionPlan: true,  hasBiophiliaPlan: false },
};

const FULL_VALUATIONS = [
  { lotSizeSqFt: 15000, assessedValue: 120000, state: 'GA', canopyPct: 30, buildingSqFt: 2200,  yearBuilt: 2005, propertyType: 'singleFamily' },
  { lotSizeSqFt: 43560, assessedValue: 400000, state: 'GA', canopyPct: 15, buildingSqFt: 5000,  yearBuilt: 1990, propertyType: 'singleFamily', zoning: 'R-1' },
  { lotSizeSqFt: 87120, assessedValue: 800000, state: 'GA', canopyPct: 40, buildingSqFt: 10000, yearBuilt: 2015, propertyType: 'singleFamily', zoning: 'MU-1' },
];

// ─── Helpers ─────────────────────────────────────────────────

/**
 * Strip non-deterministic fields (timestamps) from any deeply-nested object.
 * Must match the version in generate-snapshots.js.
 */
function normalize(obj) {
  if (obj === null) return obj;
  if (typeof obj === 'number') {
    return Object.is(obj, -0) ? 0 : obj;
  }
  if (typeof obj !== 'object') return obj;
  if (Array.isArray(obj)) return obj.map(normalize);
  const out = {};
  for (const [k, v] of Object.entries(obj)) {
    if (k === 'generatedAt' || k === 'lastUpdated') continue;
    out[k] = normalize(v);
  }
  return out;
}
// Alias for backward compatibility within this file.
const stripDates = normalize;

// ─── Tests ───────────────────────────────────────────────────

describe('EcosystemServices.calculate — snapshot parity', () => {
  for (const [name, parcel] of Object.entries(PARCELS)) {
    it(`matches snapshot for parcel: ${name}`, () => {
      resetRng(1);
      const actual = stripDates(Lib.EcosystemServices.calculate(parcel));
      const expected = snapshots.ecosystem[name];
      assert.deepEqual(actual, expected);
    });
  }
});

describe('LandAppreciation.project — snapshot parity', () => {
  PROJECTIONS.forEach((params, i) => {
    it(`matches snapshot for projection scenario ${i + 1}`, () => {
      resetRng(1);
      const actual = stripDates(Lib.LandAppreciation.project(params));
      const expected = snapshots.appreciation[i].output;
      assert.deepEqual(actual, expected);
    });
  });
});

describe('CertificationPathway.assess — snapshot parity', () => {
  for (const [name, siteData] of Object.entries(SITE_DATA)) {
    it(`matches snapshot for siteData: ${name}`, () => {
      resetRng(1);
      const actual = stripDates(Lib.CertificationPathway.assess(siteData));
      const expected = snapshots.certifications[name];
      assert.deepEqual(actual, expected);
    });
  }
});

describe('LandValuation.fullValuation — snapshot parity', () => {
  FULL_VALUATIONS.forEach((parcel, i) => {
    it(`matches snapshot for valuation scenario ${i + 1}`, () => {
      resetRng(1);
      const actual = stripDates(Lib.LandValuation.fullValuation(parcel));
      const expected = snapshots.landValuation[i].output;
      assert.deepEqual(actual, expected);
    });
  });
});

describe('Snapshot file integrity', () => {
  it('has the expected fixture counts', () => {
    assert.equal(Object.keys(snapshots.ecosystem).length, Object.keys(PARCELS).length, 'ecosystem fixture count mismatch — regenerate snapshots');
    assert.equal(snapshots.appreciation.length, PROJECTIONS.length, 'appreciation fixture count mismatch — regenerate snapshots');
    assert.equal(Object.keys(snapshots.certifications).length, Object.keys(SITE_DATA).length, 'certifications fixture count mismatch — regenerate snapshots');
    assert.equal(snapshots.landValuation.length, FULL_VALUATIONS.length, 'landValuation fixture count mismatch — regenerate snapshots');
  });
});
